/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WeeklyRouteImport } from './routes/weekly'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PhysicalRouteImport } from './routes/physical'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AcademicRouteImport } from './routes/academic'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademicCourseIdRouteImport } from './routes/academic_.$courseId'

const WeeklyRoute = WeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicalRoute = PhysicalRouteImport.update({
  id: '/physical',
  path: '/physical',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicRoute = AcademicRouteImport.update({
  id: '/academic',
  path: '/academic',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCourseIdRoute = AcademicCourseIdRouteImport.update({
  id: '/academic_/$courseId',
  path: '/academic/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic': typeof AcademicRoute
  '/dashboard': typeof DashboardRoute
  '/physical': typeof PhysicalRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/weekly': typeof WeeklyRoute
  '/academic/$courseId': typeof AcademicCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic': typeof AcademicRoute
  '/dashboard': typeof DashboardRoute
  '/physical': typeof PhysicalRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/weekly': typeof WeeklyRoute
  '/academic/$courseId': typeof AcademicCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academic': typeof AcademicRoute
  '/dashboard': typeof DashboardRoute
  '/physical': typeof PhysicalRoute
  '/settings': typeof SettingsRoute
  '/skills': typeof SkillsRoute
  '/weekly': typeof WeeklyRoute
  '/academic_/$courseId': typeof AcademicCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic'
    | '/dashboard'
    | '/physical'
    | '/settings'
    | '/skills'
    | '/weekly'
    | '/academic/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic'
    | '/dashboard'
    | '/physical'
    | '/settings'
    | '/skills'
    | '/weekly'
    | '/academic/$courseId'
  id:
    | '__root__'
    | '/'
    | '/academic'
    | '/dashboard'
    | '/physical'
    | '/settings'
    | '/skills'
    | '/weekly'
    | '/academic_/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademicRoute: typeof AcademicRoute
  DashboardRoute: typeof DashboardRoute
  PhysicalRoute: typeof PhysicalRoute
  SettingsRoute: typeof SettingsRoute
  SkillsRoute: typeof SkillsRoute
  WeeklyRoute: typeof WeeklyRoute
  AcademicCourseIdRoute: typeof AcademicCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/weekly': {
      id: '/weekly'
      path: '/weekly'
      fullPath: '/weekly'
      preLoaderRoute: typeof WeeklyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physical': {
      id: '/physical'
      path: '/physical'
      fullPath: '/physical'
      preLoaderRoute: typeof PhysicalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic': {
      id: '/academic'
      path: '/academic'
      fullPath: '/academic'
      preLoaderRoute: typeof AcademicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic_/$courseId': {
      id: '/academic_/$courseId'
      path: '/academic/$courseId'
      fullPath: '/academic/$courseId'
      preLoaderRoute: typeof AcademicCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademicRoute: AcademicRoute,
  DashboardRoute: DashboardRoute,
  PhysicalRoute: PhysicalRoute,
  SettingsRoute: SettingsRoute,
  SkillsRoute: SkillsRoute,
  WeeklyRoute: WeeklyRoute,
  AcademicCourseIdRoute: AcademicCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
